### ISSUE TITLE
Every time I launch a game in full screen, the screen turns off.

### ISSUE THREAD

**Issue by Eden365** [JPersson77/LGTVCompanion#100]
I have an issue where every time I launch a game in full screen, the screen turns off and I have to turn it on with a remote. This is a new issue and its been working fine up until now.

If I launch a game in windowed mode its fine. But if its launched in full screen, the tv turns off.

Is there a setting that I have turned on or something in windows? 

Thank you

**Comment by JPersson77** [comment]
Hi Eden, not sure why you are seeing this issue. Can you post a full log here please and indicate the timestamp when a game was launched so I can have a look at what is going on

**Comment by Eden365** [comment]
> Hi @Eden365 , not sure why you are seeing this issue. Can you post a full log here please and indicate the timestamp when a game was launched so I can have a look at what is going on
> 
> Also there was this: #90

I cleared the log and then started my game straight away. Here is what the log shows.

Tue 20:03:53 > IPC, windows monitor topology was changed. Device1:OFF 
Tue 20:03:53 > Device1, spawning DisplayPowerOffThread().
Tue 20:03:53 > Device1, HDMI1 input active.
Tue 20:03:53 > Device1, power state is: OFF.
Tue 20:03:54 > IPC, windows monitor topology was changed. Device1:OFF 
Tue 20:03:54 > Device1, spawning DisplayPowerOffThread().
Tue 20:03:55 > Device1, HDMI1 input active.
Tue 20:03:55 > Device1, power state is: OFF.

I have done no hardware changes and I also performed a fresh windows install last week. I uninstalled my GPU drivers and did a fresh install of them as well, if that matters.

**Comment by JPersson77** [comment]
Hi, so what it looks like in the log is that Device1 (your TV) has been disabled and the app is telling the TV to power off subsequently (Tue 20:03:53 > IPC, windows monitor topology was changed. Device1:OFF)

Let's try to break it down. I need much more info on what is happening

Are you on a multi-monitor system?
Can you confirm that you have enabled the topology feature in the options? I assume so as this is what powers off your TV.
Can you confirm that you have configured the topology feature properly? I e can you successfully switch between enabled and disabled state of the HDMI-output to which the TV is connected, in windows or your graphics card settings, and the TV will power on/off accordingly?

Is the TV the primary or a secondary monitor? 
Are you launching the game to be played on Device1 (your TV) or on another monitor?
When you power on the TV with the remote, is there signal, i e is there an image?

Are there more entries in the log coming directly after? Perhaps something like Tue 20:03:XX > IPC, windows monitor topology was changed. Device1:ON. I would appreciate the full log and also the config.json to be able to help better.

With my questions I am trying to understand if this is normal behaviour or not. It's a possibility that what you are experiencing is normal, if for example you have another monitor as primary and you are loading up a fullscreen exclusive game on that monitor I think windows  (depending on configurations) will potentially power off secondary screens. But if the TV is primary, and/or the only enabled monitor then there is something wrong here. Then, either there is more events coming from windows shortly after the ones turning the TV off and the timing is so tight that the app cannot power it on again (which is why I need to know if there is more in the log) or the feature is misconfigured. Or something else...

What game are you loading up? :)

**Comment by Eden365** [comment]
Thank you for the quick reply friend.

1. I am running a dual monitor setup.
2. Topology feature is enabled in options and it is automatically configured via the app.
3. TV(LG C2) is my primary monitor and all games launch on my TV. (Secondary monitor stays on desktop, no screen flashing or games attempt to launch on my secondary monitor).
4. TV successfully displays an image when using the remote (When the game launches and the LG logo comes up and turns the screen blank, everything runs as it should once I turn it back on with the remote control. If I close the game and attempt to run it again, screen will go blank)

Here is full log and config file. (I changed config.json to a txt file if thats okay)
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/10434259/Log.txt)
[config.txt](https://github.com/JPersson77/LGTVCompanion/files/10434420/config.txt)

Windows 11 Version 22H2 (OS Build 22621.1105)
Running an Asus RTX 4090

Games will load up fine with companion app uninstalled. I don't believe I've ever had windows turn off any of my monitors when gaming. Is there a setting I can check within windows?

Just tried it on multiple games. Apex legends, Team Fortress 2, SCP. Happens when they run full screen. I change the startup to run on borderless window and they load up fine. It is only happening when the game launches within full screen.

Even within the Nvida control panel with no games running. If I change scaling mode to full screen, that will still power off the TV when im just on the desktop.

If there is anything else you need or something I did not explain correctly. Please let me know.

Thank you so much :)
Eden

**Comment by JPersson77** [comment]
Thanks, good info! Congrats on the RTX 4090! :)

From your description it is clear that you are not experiencing normal behaviour. When you enter fullscreen on your C2, windows will send a broadcasted message the app is using as a starting point for determining if the topology has been changed. For this to work properly it's important that everything has been set up properly, or else the app will conclude that the device has been disabled and the TV will be powered off.

I notice this in the log: "IPC, A recent change to the system seem to have invalidated the monitor topology configuration. Please run the configuration guide in the global options again to ensure correct operation."

This means that the app has picked up that your C2 has received a new "unique identifier". This should not just happen randomly, but will fe occur when physically changing GPU. I'm sure there may be other ways to invalidate this, like maybe changing your signal chain, using CustomResolutionUtility, or swapping HDMI inputs/outputs? For what it's worth I also have a multi monitor setup with an RTX and it's perfectly stable. 

So what is going on here then? You say you accepted the automatic configuration of the topology and I can see that it's properly saved in the configuration. But we know it's wrong at this time. Was it wrong all the time you think? What happens if you rerun the configuration? If you rerun the configuration guide you should see this update in the config.json: ""UniqueDeviceKey": "\\\\?\\DISPLAY#GSMC0C8#5&38f04ad3&1&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}""

**Comment by Eden365** [comment]
Thank you! It was definitely hard to get one in stock in Australia haha

This problem has only occured once I did a fresh reinstall of windows. I completed my computer build at the beginning of December and the companion app was running fine.(same gpu and same dual setup. TV and monitor) I did a fresh install last week and the problems were occuring since then. My GPU has not been removed from the PCIE slot between windows installs.

I ran the conifguration again and my line was updated with the correct string.
"UniqueDeviceKey": "\\\\?\\DISPLAY#GSMC0C8#5&38f04ad3&1&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",

I was receiving that notification about the configuration becoming invalidated a few days ago. After I reinstalled the companion app, I no longer recieved it.

**Comment by JPersson77** [comment]
Hmm, did you paste the new string? It is the exact same as the old one?

**Comment by Eden365** [comment]
Even after I am reconfiguring it, the string is not changing. Is this normal?

**Comment by JPersson77** [comment]
Assuming you did press "apply" that is weird yes

**Comment by Eden365** [comment]
Yep, I run the configuration, it says waiting for input. I press start, and status switches to All ok!
I press finish, and then press apply.

![1](https://user-images.githubusercontent.com/95530282/212895782-4d5fd973-07ef-4d39-a6d2-a0f493d6a622.png)
![2](https://user-images.githubusercontent.com/95530282/212895806-e353318b-94b8-4eb6-83c6-81ed11334ed0.png)

Here is an updated config and log file. It does not appear that the uniquedevicekey is being changed, even after reconfigurating.

[config.txt](https://github.com/JPersson77/LGTVCompanion/files/10434847/config.txt)
[Log.txt](https://github.com/JPersson77/LGTVCompanion/files/10434848/Log.txt)

**Comment by JPersson77** [comment]
However, it looks to be working now. I see this in the log: Tue 22:09:31 > IPC, windows monitor topology was changed. Device1:ON 

Try starting a game? :)

**Comment by Eden365** [comment]
Yay! It loaded up fine now! I'm not sure what I changed? 

I reconfigured, disconnected and reconnected my HDMI cable? 
Then restarted my computer.

Both Apex and TF2 loaded into full screen all good! Thank you so much for your help! I sent you a donation for my appreciation to you and your app. It was the first program I downloaded when I built my new PC.

Issue solved! Thank you again :)

**Comment by JPersson77** [comment]
Thanks mate! Appreciated! Somehow there's gotta be a bug or some other unknown around here still though I suspect. From the log it started working 21.44. Will continue thinking about it! :)

**Comment by Eden365** [comment]
I had a thought. I'm not sure if it helps. 

But, the companion app and my computer is all configured through my ethernet IP. 

I had my ethernet cable disconnected and was using wifi over the weekend when the issues started to happen(I get better speeds on wifi vs Ethernet at the moment, but it is less stable). 

I tested it and when I switch to wifi the companion app no longer works. Could this have cause an issue with the topology configuration and it got confused?

**Comment by JPersson77** [comment]
Unlikely. But I appreciate you thinking about it. The funky part is that the app identified that the uniqueid was wrong, even though it was right, but it didn't work hehe. I'll let my mind work on it in the background :)

**Comment by Eden365** [comment]
Sounds good :) 

if it happens again, I'll let you know.

**Comment by JPersson77** [comment]
This funny and quirky issue with an even funnier and quirkier solution is resolved in the new release. Closing the issue.
