### ISSUE TITLE
Screen toogle

### ISSUE THREAD

**Issue by regeenx** [JPersson77/LGTVCompanion#106]
Is it possible to create screen on/off (power on/off) toggle shortcut using Commandline arguments? right now I did two shortcuts with arguments ("C:\Program Files\LGTV Companion\LGTV Companion.exe" -screenoff Device1; "C:\Program Files\LGTV Companion\LGTV Companion.exe" -screenon Device1) , it works but I have to use two separate buttons on my keyboard, I'd prefer one button Toggle.

**Comment by JPersson77** [comment]
Short answer: no

Long answer: unless "always ready" on 2-series models (and later presumably) the TV does not respond to queries when it is powered off. Which means that to build the "toggle" the app need to implement some logic around that indeterminate state, but at the same time it is also required to be able to turn on/off the TV within a reasonably short time frame <1 second so that it's a smooth user experience. 

Workaround: use the command line options of the app but in an autohotkey script with some global variable so that it power on and off the TV every other time the script is executed. Then you only need one button. Let me know if you need help with that and I can help.

**Comment by regeenx** [comment]
"Workaround: use the command line options of the app but in an autohotkey script with some global variable so that it power on and off the TV every other time the script is executed. Then you only need one button. Let me know if you need help with that and I can help."

yes, some advice needed :)

**Comment by JPersson77** [comment]
Sure no problem. Here are some examples to get you going.

Windows batch script (.BAT) 
Put it in its own folder where you have write access (so not the same folder as LGTV companion). Also note that if you want the TV to power off you need to use -power and -poweroff rather than -screenon and -screenoff
`IF EXIST "togglefile.log" GOTO Toggle_On

:Toggle_Off
ECHO LG_OFF >"togglefile.log"
"C:\Program Files\LGTV Companion\LGTV Companion.exe" -screenoff Device1
GOTO:EOF

:Toggle_On
Del /Q "togglefile.log"
"C:\Program Files\LGTV Companion\LGTV Companion.exe" -screenoff Device1
`

And here is an example using autohotkey:
`F9::
T := !T
If T
 Run, "C:\Program Files\LGTV Companion\LGTV Companion.exe" -screenoff Device1
else
 Run, "C:\Program Files\LGTV Companion\LGTV Companion.exe" -screenon Device1
return`

**Comment by regeenx** [comment]
works like a charm! thx you!
