### ISSUE TITLE
repeatedly told to update even after updating to latest

### ISSUE THREAD

**Issue by fiafied** [JPersson77/LGTVCompanion#107]
even after updating to 2.0.0, I am still receiving notifications to update

**Comment by JPersson77** [comment]
Hi, that sounds like the daemon did not update properly (since the daemon is responsible for creating the desktop notifications). If you open the main UI, do you also see a clickable link urging you to upgrade? 

To verify that the latest version of all files were properly installed you can do this:
-LGTV Companion.exe (UI) - check the version number in the title bar
-LGTVdaemon.exe - open a command prompt and execute "c:/program files/lgtv companion/LGTVdaemon.exe -show" and check the version number in the titlebar of the window that opens
-enable the log and see what version number the service report.

Can you confirm all thre report 2.0.0 ?

**Comment by fiafied** [comment]
the main UI shows v2.0.0 in the title & no upgrade prompt

LGTVdaemon.exe shows v2.0.0

the log shows v2.0.0 for the service

**Comment by JPersson77** [comment]
So all three are the correct versions. Since main UI does not show an upgrade prompt it's not so likely there is a bug in the code path for downloading the version numbering and parsing it. Can it be that the notification is some left over from the first time it was shown (when you were still on the old version)? Does it disappear after a reboot?

**Comment by fiafied** [comment]
oh it looks like there are 2 LGTVdaemon.exe processes running, 1 is v2.0.0 in the normal install location, 1 is v1.9.0 in `Windows\Installers\{some-GUID}\`

**Comment by JPersson77** [comment]
That would explain the notification, good catch! Is v1.9 autorunning in that location as well? I dont know why v 1.9 was installed there (or if it even was installed there) but I would like to understand if there is a bug with the installer. Can I assume you didn't install v1.9 in that location? What os and build are you running? Is the v2.0 daemon autostarting with Windows?

**Comment by fiafied** [comment]
oh okay, I figured it out. my Control Center app from my OEM (Acer Care Center) was trying to manage startup apps, and was autostarting the 1.9 daemon. when I disabled that & removed the associated scheduled tasks, it started working normally. thanks for your help!

**Comment by JPersson77** [comment]
Happy you figured it out! Thanks too!!
