### ISSUE TITLE
Screen goes black briefly shortly after waking from idle mode

### ISSUE THREAD

**Issue by Jason-GitH** [JPersson77/LGTVCompanion#113]
I've noticed over past several versions that my LG TV (C2) will occasionally briefly flash a blank screen immediately after moving my mouse to turn the screen back on after the idle mode has been triggered.

**Comment by JPersson77** [comment]
Hi @Jason-GitH can you please enable logging and upload config.json and the log to pastebin or similar and paste a link here. Also please indicate the time when the issue occurs so I can have a look at what is going on

**Comment by Jason-GitH** [comment]
> Hi @Jason-GitH can you please enable logging and upload config.json and the log to pastebin or similar and paste a link here. Also please indicate the time when the issue occurs so I can have a look at what is going on

Hi, it finally happened again. Here is most recent log: [https://pastebin.com/xC3XyQzp](url)
Here is config.json: [https://pastebin.com/d91DvvxA](url)

**Comment by JPersson77** [comment]
Hi @Jason-GitH i cannot consolidate the log with the description of the issue. At 21:35:46 and also 21:50:01 I see that user idle mode is triggered and released simultaneously (within a second). To me this looks like you were idle/afk one minute (the configured time to wait before triggering user idle mode) and just when the idle mode is triggered the mouse or kb was used thereby unsetting user idle mode. This would lead to a short blanking of the screen obviously. Is this your issue?

Otherwise, I cannot see from the log substract that you were in user idle mode for a period of time before exiting user idle mode, when the flashing occurred. 

Can you clarify please on the above?

**Comment by Jason-GitH** [comment]
Basically, the screen will blank, I move mouse, the screen comes back on, the screen blanks very briefly, and then it remains on without any further blanking until the next idle mode activates. However, this only happens sporadically. It is possible there is some confounding issue because I just remembered that I do have Windows set to display a blank screen saver after 1 minute as well.

**Comment by JPersson77** [comment]
Yeah I think you are right. When the issue occurs the windows screensaver engage so you reach for the mouse to disable it and simultaneously the user idle mode of the app trigger and release instantly. 

I'm guessing you have more monitors (non LG TVs) connected to your system in which case it might make sense to have the windows screensaver enabled so all screens blank at the same time. If you only have the LG though I would urge you to disable the windows screensaver as the user idle mode should cover your needs.

**Comment by JPersson77** [comment]
Hi @Jason-GitH any further feedback wrt this issue?

**Comment by Jason-GitH** [comment]
> 

Hi, No, thank you. Thanks for all your great work with this program. Btw, do you use ColorControl and if so, do you recommend disabling their power management options? They seem much more complicated than what you have set up, so I prefer LGTVCompanion's power management.

**Comment by JPersson77** [comment]
Hi thanks too! Yes I use Color Control for controlling dithering of my nVidia gfx card, when needed. I would recommend you stick with only one or the other for power management to avoid interference.

**Comment by JPersson77** [comment]
closing  - resolved
