### ISSUE TITLE
LG C2 42 won't wake from sleep

### ISSUE THREAD

**Issue by iggy097** [JPersson77/LGTVCompanion#114]
First, thanks for making this app. I've just purchased an LG c2 42 and installed your app, setup as instructed but when running the test, I can't get the TV to come out of sleep automatically - I have to use the power button.
Any suggestions?

**Comment by JPersson77** [comment]
Hi @iggy097, thanks too! If the TV will power off but not power on it's most likely because wake-on-lan (WOL) does not work properly.

Can you confirm you have setup the TV so that it will respond to WOL? Bullet point 1 here: https://github.com/JPersson77/LGTVCompanion#installation-and-usage

If the above is configured correctly have a look at all the troubleshooting tips here: https://github.com/JPersson77/LGTVCompanion#troubleshooting especially regarding verifying the mac address and trying the other network options. 

If it still does not work enable logging and upload it and config.json to pastebin and paste links here and I will have a look

**Comment by iggy097** [comment]
This did it - thanks :) not sure how I missed it

   - Ensure that the TV can be woken via the network. For the CX line of
   displays this is accomplished by navigating to Settings (cog button on
   remote)->All Settings->Connection->Mobile Connection Management->TV On with
   Mobile, and then enable 'Turn On via Wi-Fi'. For C1 and C2 it's All
   Settings->General->Devices->External Devices->TV On With Mobile->Turn on
   via Wi-Fi.

**Comment by iggy097** [comment]
Last question, does LGTV Companion need to be minimized in the desktop tray
or can I close it out when done?

**Comment by JPersson77** [comment]
That's great! You can safely close the options UI. It is only for configuring the service and daemon running in the background.

**Comment by JPersson77** [comment]
resolved, closing the issue
