### ISSUE TITLE
[Request] Enable HDR in windows when opening game

### ISSUE THREAD

**Issue by lordraiden** [JPersson77/LGTVCompanion#117]
I know is a little bit out of the current scope but that setting would be quite useful.

I work with an LG C2 and I do it with HDR disable, but for gamming at least for specific games I always have to go to windows settings and enable HDR.

It would be nice to have a setting to auto enable HDR in windows for specific processes and disable once the process is closed.

Is the functionality of this software but it would be nice to have everything included in 1 app, and I guess it shouldn't be complex to implement and will be useful for many people using LG as a monitor.

**Comment by dechamps** [comment]
> I work with an LG C2 and I do it with HDR disable, but for gamming at least for specific games I always have to go to windows settings and enable HDR.

Have you considered simply leaving the Windows HDR setting always on? This is what I do.

With HDR on, Windows will automatically convert SDR content so that it is accurately rendered within the HDR container. I have personally verified (using a color meter) that Windows does this correctly (i.e. the resulting SDR colorimetry is accurate, or at least not significantly less accurate than SDR mode). In fact, SDR content arguably looks better that way because it works around the SDR black crush issue that affects many LG OLEDs (including my G1).

Given this, there is no downside to leaving HDR always on, even when using SDR apps.

**Comment by JPersson77** [comment]
Hi @lordraiden, I think you are right that it's not exactly in scope for the application. There are a few alternatives out there already which does what you want - you may want to check out https://github.com/Codectory/AutoActions or https://github.com/bradgearon/hdr-switch/

WIN+ALT+B is also a very useful shortcut to remember.

But I think you consider doing what @dechamps suggests and keep windows HDR enabled at all times since you have an OLED. There are really only benefits,. One being not having to toggle HDR on a per-game-basis.

**Comment by lordraiden** [comment]
hi @dechamps HDR is too bright and uncomfortable if you spend too much time browsing or with word, excel, etc. At least in OLED monitors. At the end there is a lot of contrast with black text and white background.

@JPersson77 thanks for the WIN+ALT+B tip
This one looks nice https://github.com/Codectory/AutoActions although it would be have all the features in one app.

**Comment by JPersson77** [comment]
closing this since there is not an issue with the app
