### ISSUE TITLE
Ethernet Cable Connected LG C1 TV Not Powering on using program's manual and automatic command

### ISSUE THREAD

**Issue by Ashar003** [JPersson77/LGTVCompanion#12]
I can turn off the tv fine manually and automatically, and , surprisingly, the tv turns on(from off-state) when I issue a manual turn off command.

I have tried all three options in the configure menu.
The logs show that the program is able to communicate with the display:

*My setup : I have shifted DHCP giving capability from my home router to a raspberry-pi running PiHole *

*The mac-addresses match in the program, PiHole, and on the tv*
*The LG C1 is on latest firmware update  - 03.20.80 *
***I removed the mac address and client key***

Wed 12:25:18 > LGTV Companion Service started (v 1.4.2) ---------------------------
Wed 12:25:18 > Configuration file successfully read
Wed 12:25:18 > Data path: C:\ProgramData\LGTV Companion\
Wed 12:25:18 > Device1, [LG] webOS TV OLED48C1PUB, with IP 192.168.1.51 initiated (Enabled:yes, WOL:1, Pairing key:, MAC:   )
Wed 12:25:18 > Host IPs detected: 172.23.112.1, 172.31.80.1, 172.27.128.1, 192.168.1.74
Wed 12:25:18 > Setting shutdown parameter level 0x1E1
Wed 12:25:18 > ** System requests displays ON.
Wed 12:25:18 > Device1, spawning DisplayPowerOnThread().
Wed 12:25:18 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:18 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:18 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":""}}
Wed 12:25:18 > Device1, established contact: Display is powered ON.  
Wed 12:25:20 > IPC command received: -poweroff Device1
Wed 12:25:20 > Device1, spawning DisplayPowerOffThread().
Wed 12:25:20 > Device1, established contact: Display is powered OFF.  
Wed 12:25:20 > Device1, repeating WOL broadcast ended
Wed 12:25:24 > IPC command received: -poweron Device1
Wed 12:25:24 > Device1, spawning DisplayPowerOnThread().
Wed 12:25:24 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:24 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:24 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":""}}
Wed 12:25:24 > Device1, established contact: Display is powered ON.  
Wed 12:25:26 > IPC command received: -poweron Device1
Wed 12:25:26 > Device1, spawning DisplayPowerOnThread().
Wed 12:25:26 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:26 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:26 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":""}}
Wed 12:25:26 > Device1, established contact: Display is powered ON.  
Wed 12:25:26 > Device1, repeating WOL broadcast ended
Wed 12:25:27 > IPC command received: -poweron Device1
Wed 12:25:27 > Device1, spawning DisplayPowerOnThread().
Wed 12:25:27 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:27 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:27 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":""}}
Wed 12:25:27 > Device1, established contact: Display is powered ON.  
Wed 12:25:28 > Device1, repeating WOL broadcast ended
Wed 12:25:28 > IPC command received: -poweron Device1
Wed 12:25:28 > Device1, spawning DisplayPowerOnThread().
Wed 12:25:28 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:28 > Device1, repeating WOL broadcast started to MAC:  using network broadcast: 255.255.255.255
Wed 12:25:28 > Device1, response received: {"type":"registered","id":"register_0","payload":{"client-key":""}}
Wed 12:25:28 > Device1, established contact: Display is powered ON.  
Wed 12:25:29 > Device1, repeating WOL broadcast ended
Wed 12:25:29 > IPC command received: -poweroff Device1
Wed 12:25:29 > Device1, spawning DisplayPowerOffThread().
Wed 12:25:30 > Device1, established contact: Display is powered OFF.  
Wed 12:25:30 > Device1, repeating WOL broadcast ended

**Comment by JPersson77** [comment]
Hi Ashar003,

Thanks for your report. I see that you confirm you have tried all three network options in the device configuration dialog. Primarily no 3 should be the preferred option. From your description it sounds to me like the app can communicate directly with the TV but broadcasted wake-on-lan (WOL) packets does not reach the TV. (Broadcasted WOL-packets are what turns the TV on). In this case I would probably urge you to review your home network and router as it seems that WOL-packets cannot be distributed on the LAN. We could for example try sending WOL-packets using https://wol.aquilatech.com/help/properties/ to see if it can wake the TV. However....

When I look at the log mostly it looks totally normal. The TV responds normally to the app quering for its power on status (f.e. "Wed 12:25:28 > Device1, established contact: Display is powered ON."). This is basically the TV saying "yep I'm ON". (in contrary to what you see)

So what does this mean? From the info I have right now I suspect that the TV was turned off (timestamp 12.25.20) but went into pixel refresh (which happens every now and then). When the TV is performing a pixel refresh it is essentially still on and it continues to reply to the app as it is being queried (this is what can be seen in the log). So ok the TV is still on but why does the display not turn on then? Well, it should be one of two things. either the WOL-packet (which, again, is what actually tell the TV to turn on) does not reach the TV and then we are back to what I started saying in paragraph one, or either it can be that the TV refuses to turn on the display on while pixel refreshing. Assuming the TV is undergoing pixel refresh it will eventually turn off properly once its finished and this can be heard because the internal power relay clicks off (can take 10secs or 60minutes). So try waiting a bit longer and see what happens, and that shall help us understand what goes wrong.


Also, it's not actually entirely surprising that the TV will turn on from a power off command, howwever illogical it may seem, but it seems that, on some TVs, commands issued to the TV after a power off command, but before the finishing of a pixel refresh will (or at least sometimes) wake the display. This can usually only be triggered through the manual command line interface, In essence this might indicate that we are, again, looking at a scenario where your LAN discards broadcasted WOL.

Please observe the issue a bit longer and we'll see how to proceed.

**Comment by Ashar003** [comment]
Hi JPersson77,

About the weird thing, I entered the mac address twice out of despair lol.

I also tested the on command having pixel refresh schedule disabled.

I'll look into my lan soon.

I forgot to mention that, as I was playing around with option 3, when it's set at 255.255.255.0(to mimic the tv's subnet setting) 
 ,in the log, it's transformed to 192.168.1.255.

Thanks

**Comment by JPersson77** [comment]
Ah, thanks, that explains the two WOLs. 

Not sure if you can really disable pixel refresh, but regardless it shouldn't pixel refresh all the time of course.

Subnet mask 255.255.255.0 in your case equals 192.168.1.255 as the broadcast adress so that looks correct. You may want to go to an admin command prompt and type "ipconfig /all" just to verify that the subnet mask is accurate.

See if you can observe behaviour a bit longer. Can you also confirm you have the "wake-on wifi" option enabled in the TV settings? (see below)

_Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile and enable 'Turn On via Wi-Fi'._

**Comment by dechamps** [comment]
> _Ensure that the TV can be woken via the network. For the CX line of displays this is accomplished by navigating to Settings (cog button on remote)->All Settings->Connection->Mobile Connection Management->TV On with Mobile and enable 'Turn On via Wi-Fi'._

On the C1 that's All Settings > General > Devices > External Devices > TV On With Mobile > Turn on via Wi-Fi.

**Comment by JPersson77** [comment]
@Ashar003 hi mate, any feedback wrt the above?

**Comment by Ashar003** [comment]
Hello @JPersson77,

My apologies for not responding sooner.
It resolved itself shortly after that day in December - 22nd.
