### ISSUE TITLE
LG C1 turning on when I start my PC that is only attached to LG C2

### ISSUE THREAD

**Issue by Chad711** [JPersson77/LGTVCompanion#120]
I have a LG C2 for my PC and a LG C1 for my PS5 (HDMI 1). I sometimes use the LG C1 for PC gaming too (HDMI 3). I have them both configured in the LG Companion.  The LG C1 I have the box ticked to only "process power the screen off events when the display input is set to HDMI 3" (PC). However whenever I boot up my PC both my C2 and C1 boot up. Is there a way to make it so the C1 only boots up if that HDMI 3 is the current input or just not have it turn on when the PC boots? The way this is currently working it turns them both on and therefore turns my PS5 on due to a PS5 setting I'm using to actively wake the PS5 when TV turns on.

**Comment by JPersson77** [comment]
Hi Chad, this has been requested previously and I think it could fit with the scope of the application since it kind of mimics how monitors work with enabling different inputs. It does however require "always ready" on the TV which can only be found on 2-series models so your C1 would be out of scope unfortunately. "Always ready" is needed so the PC can query the current input of the TV before turning it on. This is still unverified if it actually works.

However, since your use case is to not use the C1 at all times with the the PC it would make sense to disable automatic management for the C1 and instead create some shortcut that you click when you want to use the C1 with the PC. The shortcut should enable automatic management and power on the C1. Please see the command line reference.

**Comment by Chad711** [comment]
Ok understood, thank you. I actually didn't even notice my C1 doesn't have "always ready" like the C2.
