### ISSUE TITLE
2.10 C2 no longer powers off 

### ISSUE THREAD

**Issue by atledreier** [JPersson77/LGTVCompanion#123]
After the latest update my C2 no longer powers down when idle or shutoff. 
When running the test I get no errors, but the screen does not shut off.

The screen starts with the computer.

**Comment by JPersson77** [comment]
Hi @atledreier, it sounds like the app can not properly communicate with the TV. The most typical reason for your issue is that the IP of the TV has changed. Please verify that the configuration is still correct. 

If this does not resolve your issue please enable the logging and paste the log and config.json on pastebin or similar and paste the link here and I will have a look

**Comment by weenan** [comment]
> After the latest update my C2 no longer powers down when idle or shutoff. When running the test I get no errors, but the screen does not shut off.
> 
> The screen starts with the computer.

This is exactly what happened when LG firmware 03.30.30 was released I think. If your firmware is 03.30.30 or newer you need to run LGTV Companion build 2.0 or newer. My guess is you are using build 1.x of LGTVCompanion

**Comment by atledreier** [comment]
It was the IP. Somehow my static IP rule had changed in my router.

All good now, thanks for the tip! :-)
