### ISSUE TITLE
Subnet issues

### ISSUE THREAD

**Issue by kyalejamison** [JPersson77/LGTVCompanion#139]
![16840060152556391631410842396258](https://github.com/JPersson77/LGTVCompanion/assets/85897619/4c96be6c-c98f-475a-bc51-372e6599e3f8)
I've been using your program for a few years now and love it but just recently I've been getting this message and it's broken the functionality of the program and I can't figure out what in earth is causing it

**Comment by JPersson77** [comment]
Thanks, the message is a warning message indicating that your pc and tv is not on the same subnet. This can be an issue since the tv is powered on by means of wake on lan, which is layer 2, i e same subnet. It is however just a warning.

If the app has worked previously i would try to figure out if something changed on your lan. Maybe also upload your config.json and log.txt to pastebin and paste links here and i can have a look

**Comment by kyalejamison** [comment]
im not exactly sure what happened but i let it sit overnight and came back in the morning and everything is working as usual lol im thinking whatever was going on had to do with my ethernet and it reset itself maybe. thanks for the response though
