### ISSUE TITLE
Doesn't work when turning off/sleeping windows

### ISSUE THREAD

**Issue by EeroOit** [JPersson77/LGTVCompanion#145]
I have issue that LGTVCompanion works and turns on my LG C2 when turning computer on, but when shutting down my computer it doesn't turn it off. Before it used work fine.

**Comment by JPersson77** [comment]
This issue has  been reported and will be fixad in the next release. Let me know how  the next version works please

**Comment by Jimez77** [comment]
Hi JPersson77. I have a weird issue where my PC is set to turn monitor off after anything longer than 1 minute, it goes to always power on mode without wallpaper but then turns back onto HDMI straight away and then show images on the screen. If I set my pc to turn monitor off after 1 minute it works perfectly. Screen goes black with blue light on. I move my mouse and its back on again. I installed the 2 previous versions, but it is still happening. Below are the logs, hoping you could have a look?

Thu 14:37:34 > ** System requests displays OFF(DIMMED).
Thu 14:37:34 > Device1, spawning Thread_DisplayOff().
Thu 14:37:34 > Device1, [DEBUG] (SSL) OFF response 1: {"type":"registered","id":"register_0","payload":{"client-key":"dbb1e75c4b71ee878526bd143f50b6b8"}}
Thu 14:37:34 > Device1, [DEBUG] (SSL) OFF response 2: {"type":"response","id":14,"payload":{"state":"Active","returnValue":true}}
Thu 14:37:34 > Device1, [DEBUG] (SSL) OFF response 3: {"type":"response","id":15,"payload":{"returnValue":true,"appId":"com.webos.app.hdmi1","processId":"","windowId":""}}
Thu 14:37:34 > Device1, HDMI1 input active.
Thu 14:37:35 > Device1, [DEBUG] (SSL) OFF response 4: {"type":"response","id":16,"payload":{"returnValue":true}}
Thu 14:37:35 > Device1, power state is: OFF.
Thu 14:37:49 > ** System requests displays OFF.
Thu 14:37:54 > ** System requests displays ON.
Thu 14:37:54 > Device1, spawning Thread_DisplayOn().
Thu 14:37:54 > Device1, repeating WOL broadcast started to MAC: 805B657E4ABC using IP address: 192.168.1.114
Thu 14:37:54 > Device1, Best route to IP - interface index 14 LUID 1689399632855040 route protocol 2
Thu 14:37:54 > Device1, [DEBUG] (SSL) ON response 1: {"type":"registered","id":"register_0","payload":{"client-key":"dbb1e75c4b71ee878526bd143f50b6b8"}}
Thu 14:37:54 > Device1, [DEBUG] (SSL) ON response 2: {"type":"error","id":17,"error":"500 Application error","payload":{"returnValue":false,"state":"Active","errorCode":"-102","errorText":"The current sub state must be 'screen off'"}}
Thu 14:37:54 > Device1, [DEBUG] (SSL) ON response 3: {"type":"response","id":18,"payload":{"state":"Active","returnValue":true}}
Thu 14:37:54 > Device1, power state is: ON
Thu 14:37:55 > Device1, repeating WOL broadcast ended

**Comment by JPersson77** [comment]
v3.0.7 includes a fix for this

**Comment by JPersson77** [comment]
any feedback on v 3.0.78 or the new 3.1.5 and the new shutdown timing option?

**Comment by EeroOit** [comment]
Monitor shutdown doesn't function for me even with the latest version using
the early option.

pe 30. kesäk. 2023 klo 18.31 JPersson77 ***@***.***>
kirjoitti:

**Comment by JPersson77** [comment]
Hi @EeroOit can you then please enable logging, paste a log on pastebin and copy the link here. Paste a link to config.json as well please. They are both in c:/programdata/lgtv companion/

**Comment by EeroOit** [comment]
https://pastebin.com/bhZMZLnA

**Comment by JPersson77** [comment]
Hi, these error messages indicate that the app cannot connect to the TV.:

`Fri 20:09:46 > Device1, WARNING! Thread_DisplayOn(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond [system:10060 at D:\a\LGTVCompanion\LGTVCompanion\vcpkg_installed\x64-windows-static\x64-windows-static\include\boost\asio\detail\win_iocp_socket_service.hpp:632:5 in function 'connect']`

The TV turns on because the WOL package reach the TV. Are you using a wired/wifi connection with the TV? Can you confirm you are using the appropriate IP of the TV which corresponds to the wired/wifi nic of the TV?. 

I think it's likely it is something on your system, network or in the configuration of the app that is erroneous. Maybe try restarting the router, switches, access points

**Comment by EeroOit** [comment]
Deleting the config file fixed the issue for me.
