### ISSUE TITLE
Screen goes to black during video

### ISSUE THREAD

**Issue by PlayingKarrde** [JPersson77/LGTVCompanion#209]
Much like the issue raised regarding idle detection with controllers through steam (which I also experience), when watching videos (within Firefox) or when in a video chat (specifically through the Teams app) it seems the idle detection kicks in and the screen goes black, forcing me to move the mouse to bring it back.

I'm not really sure how to debug this but happy to provide any extra information or do any testing if necessary.

I should add I'm using Windows 11 with an LG C3 42" on the latest firmware.

**Comment by JPersson77** [comment]
Hi @PlayingKarrde the idle issue with steam is that when steam input is active any connected controllers will not count towards resetting the windows idle mechanisms so the screen will go to blank during a game, even though a controller is being used.

Can you confirm that the issue you are facing is that the screen goes blank even though you are using the mouse/kb while watching a video or in teams? Because I'm not sure I'm reading it like that.

**Comment by JPersson77** [comment]
Hi, any feedback wrt the above?

**Comment by JPersson77** [comment]
Closing due to lack of feedback. Please feel free to reopen as needed
