### ISSUE TITLE
No localised restart string in global settings

### ISSUE THREAD

**Issue by madsession** [JPersson77/LGTVCompanion#231]
Hi,

LG OLED C3 
OS Windows 11 Pro 22631.3880
Swedish language

I checked the localised restart strings and I only have "avsluta" in the string wich is shut off.
There is no restart (starta om) to check.

I tested and changed Timing to delayed and that seemed to work fine during regular restarts, the TV was still on when it booted back into windows. But I assume if I do an windows update it will take too long and TV will turn off?

Any idea why no other strings is added for me and is there anything more I can do to help?

**Comment by madsession** [comment]
Just to add, I saw that there is an google doc for user input. But Swedish was implemented in v 3.5.0 so I assume this is a diffrent issue.

**Comment by madsession** [comment]
Hope its ok to ask this in my original thread but I also had another question.

I dont really like "Always ready" function so I have this disabled. I tried the settings anyway. Did the automatic configuration and applied the settings. I switched to extended with Ctrl+P so I had my two monitors instead. (Display 1&2)

It worked pretty good with always ready option disabled. The TV turned off. If I swithed back to "other projector or what it says in english" the TV automatically turned on again. The only problem is that when I had my two monitors on and the signal to TV (Display 3 off) and did a restart, it booted to the monitors but TV still automatically turned on. (I also tried the restore config immediatly at logon screen)

I see in config that there is an option for process power when you have an input source for TV to a specific HDMI. But isnt it also possible to add a function to only send a wake command IF for example display 3 is active in windows? (Maybe this is why always ready has to be on TV, but thought I ask if this option hasnt been thought of before.)

**Comment by JPersson77** [comment]
Tjena @madsession, I did not yet run into "avsluta" but will add it to the list. The reason you do not see any other "restart words" is because they have been added to an internal list/dictionary (i.e swedish stäng av, starta om etc). You should keep "avsluta" unchecked since it does not refer to the system restarting. The google doc you mentioned is still active and open for input fyi.

I dont see a specific issue in messages 1 and 2 above, but please clarify if there is an issue that I can address.

"Always ready" enforce that the hdmi connection is kept between the PC and the TV, even when the TV is powered off. This means that Windows can, at all times, see that a display is connected. Like a normal pc-monitor.  

When "always ready" is disabled Windows does not see the powered off TV, and it is therefore not possible to enable, in windows, the respective hdmi- output. 

This is the reason why support for monitor topology in the app list "always ready" as a requirement. It may however still work during certain circumstances.

With regards to waking up the TV only when it is attached - currently monitor topology support needs to be enabled and "restore config on boot", and of course implicitly "always ready" needs to be enabled. 

However, it is also possible to detect attached devices via another method (wmi) and I will look into that sometime in the future. Possibly a WMI query cab make the topology support better/more complete/more reliable

**Comment by madsession** [comment]
Thanks for the answer. I will close the ticked for now and let you know in the future if there is any problem with TV turning of during window updates. Hopefully it works as intended with the delay when updating.

Even the current multi-monitor function works pretty good as is for me with always ready disabled. Im really happy with this app either way. Look forward to potentially future updates to make it even better.  :)
