### ISSUE TITLE
[BUG] LGTVsvc.exe preventing PC from sleeping

### ISSUE THREAD

**Issue by alimbada** [JPersson77/LGTVCompanion#233]
### Describe the bug

The `LGTVsvc.exe` is preventing the PC from sleeping. My PC is set to go to sleep after 30 minutes of inactivity.

This is the output from `powercfg -requests`:

```
DISPLAY:
None.

SYSTEM:
[SERVICE] \Device\HarddiskVolume4\Program Files\LGTV Companion\LGTVsvc.exe (LGTVsvc)

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.
```

I am using version 3.4.0 installed via WinGet and remains the latest version on WinGet (which itself is an issue; see #230)

### How to reproduce the bug?

Set power options in Windows to go to sleep after 30 minutes.

### What was the expected behavior

PC should go to sleep.

### What is your system?

e.g. Win 10, build 19045.4651, LG OLED C2

**Comment by JPersson77** [comment]
Hi @alimbada, 

currently on holidays but will have a look in a few weeks. The app request the system to stay awake during certain key events, to buy some additional time for communicating with the TV, but this should be in the fractions of a second. Is the error intermittent or is it 100% reproducible on your system? The issue is not reproducible on my system following the steps outlined above. so some additional troubleshooting is probably needed.

**Comment by alimbada** [comment]
The error seems to be intermittent. I rebooted recently and haven't seen the issue since then. I normally put my machine in sleep state when not in use and only reboot if necessary.

**Comment by JPersson77** [comment]
Hi @alimbada did the issue reoccur for you?
