### ISSUE TITLE
Only Process Events If Active

### ISSUE THREAD

**Issue by pltrant** [JPersson77/LGTVCompanion#26]
Great program!  But is it possible to only have it process events if the PC that it is running on actually has an active HDMI connection?  Not sure if that's possible to detect.  Specifically, my use case is that I use a KVM switch and PC1 runs the LGTVCompanion and will send the shut off command after a few minutes of inactivity.  But if I switch to PC2 and am currently using it, the TV is then shut off since PC1 send the shut off command.  If the LGTVCompanion could detect that PC1 doesn't currently have an active HDMI connection, there's no need for it to process any events or send commands.

**Comment by JPersson77** [comment]
Would be nice. Adding as a feature request

**Comment by dechamps** [comment]
One way to solve this problem is to use LGTVDeviceListener, a tool I just published: https://github.com/dechamps/LGTVDeviceListener

The idea is that, instead of routing the video through the KVM, you can connect your devices to the TV directly and then have LGTVDeviceListener switch the TV input automatically when you switch the keyboard/mouse USB input.

**Comment by JPersson77** [comment]
hi @pltrant I have a beta-version for you to test. Let me know and I will provide a link.

**Comment by JPersson77** [comment]
Please check out the latest release which should do what you want: [Releases](https://github.com/JPersson77/LGTVCompanion/releases)

**Comment by JPersson77** [comment]
Closed issue because it was implemented
