### ISSUE TITLE
Turning off TV automatically put PC in Sleep mode (Enhanced feature)

### ISSUE THREAD

**Issue by WilliamLeGod** [JPersson77/LGTVCompanion#33]
Just like Xbox Seri X and PS5, turning off TV will automatically put them into rest/standby mode. Is this possible to set such feature for PC?

Thanks!

**Comment by JPersson77** [comment]
For PS5 it works due to HDMI-CEC. It is possible to sort of emulate with LGTV companion but it would only work under certain 'circumstances' so I don't think it's a feasible feature to add.

Circumstances include the PC constantly checking power status with the TV, like every second, and the other is that the TV function to automatically power off after X hours probably needs to be set to disabled by the user, to avoid the machine being powered down when the TV is auto-powered off.
