### ISSUE TITLE
LGTVCompanion stopped automatically turning TV off/on

### ISSUE THREAD

**Issue by joebeem** [JPersson77/LGTVCompanion#39]
Hello,

I have had LGTVCompanion working on my PC for several weeks, but within the past week, I noticed my TV is no longer automatically turning on/off as it had been. This is a little odd to me because I don't think I changed anything. 

While attempting to diagnose the issue, I discovered that if I manually restart the LGTVCompanion service,  the TV will turn on every time. Similarly, if I open the LGTVCompanion application and manually click the "Turn On" button, the TV will also turn on every time. For some reason, it just won't automatically turn off/on like it had been doing for several weeks. 

I am running Windows 10 19044.1806 and using an LGOLED48C1PUB. 

Has this behavior been seen before by others? 

[LGTVlog.txt](https://github.com/JPersson77/LGTVCompanion/files/9086138/LGTVlog.txt)

**Comment by dechamps** [comment]
From your log the thing that jumps out at me is that the TV's IP address (`192.168.20.13`) doesn't seem to be on any of your local subnets. Did you put the TV on a separate network segment on purpose?

Can you provide a log where you successfully turn on the TV (manually) for comparison?

**Comment by joebeem** [comment]
I apologize for the delay. 

I do have it on a separate subnet on purpose. I bought a router which supports vlan's and I have plans to implement firewall rules to isolate "IOT" devices from my important computers as a layer of security. It was also working in this exact setup for several weeks and currently works if I manually restart the LGTVsvc windows service. 

Attached is a log from a few minutes ago.

[lg-log.txt](https://github.com/JPersson77/LGTVCompanion/files/9160418/lg-log.txt)

**Comment by dechamps** [comment]
Sorry, I must have been confused - your first log shows the TV being successfully turned on, apparently because you restarted the service. Can you produce a log capturing a case where the TV does NOT turn on?

**Comment by joebeem** [comment]
It turns on every time if I do it manually, but as an example, when I sat at my desk this AM and my monitors woke up, the LG tv did not turn on like it had been. Perhaps this log (the entire log file) might contain some information. If not, what would be the best way to attempt to get logs for this behavior?

[lg-full-log.txt](https://github.com/JPersson77/LGTVCompanion/files/9161695/lg-full-log.txt)

**Comment by dechamps** [comment]
It's difficult to understand what's going on in your log because it all looks normal - LGTVCompanion attempts to turn on the display, and 20 seconds later it turns on, every single time. Either the log is misleading because you are turning on the display manually (which makes the log look like LGTVCompanion managed to turn it on but it was actually you), or there is actually no log for the failed attempts because LGTVCompanion does not even wake up (i.e. it doesn't understand that it needs to turn on the TV and so doesn't write anything to the log).

What I would suggest is writing down the precise timestamp at which the issue occurs, and then wait for at least 1 minute before doing anything else (such as restarting the service or turning on the TV manually). Then see if there are log entries around that timestamp.

**Comment by JPersson77** [comment]
hi @joebeem any feedback on precise timestamps and a an updated log so the issue can be further looked into?

**Comment by JPersson77** [comment]
Closing due to missing feedback
