### ISSUE TITLE
TV does not turn off on shutdown

### ISSUE THREAD

**Issue by mbushnaq00** [JPersson77/LGTVCompanion#5]
Hi,

I have configured the app to successfully turn on and off, however when I try to shut down my PC nothing happens. The app turns off the TV only when the display is timed out or when the PC goes on standby. I also try fiddeling with the "restart, shutdown, power off" option in the app but the issue remains.

Kindly note that I have fast-startup disable due to bootup issues

Log details:

```
Fri 12:04:07 > Event subscription callback: system shut down detected.
Fri 12:04:13 > ** System is shutting down.
Fri 12:04:13 > Device1, spawning DisplayPowerOffThread().
Fri 12:05:00 > LGTV Companion Service started (v 1.2.0) ---------------------------
Fri 12:05:00 > Configuration file successfully read
```
The line "Device1, established contact: Display is powered OFF. " is present only when going on standby or display is timed out, but missing from the shutdown event

**Comment by JPersson77** [comment]
Hi again, I suspect this issue may potentially have to do with timing particular to your system when shutting down. I think it's for example not guaranteed that windows will spawn new threads when the system is shutting down. Which may be the issue. Since I cannot really replicate this bug myself, would you be up for helping me test a patched version to try and slightly defer the service shutting down some which might help with this. And also I will just add some more detailed logging to determine what actually goes wrong. If you want to help with that please paste your email adress here (sufficiently obfuscated of course) and we can talk. Seems to be no way of sending direct messages on github unfortunately. Thanks in advance

**Comment by mbushnaq00** [comment]
> Hi again, I suspect this issue may potentially have to do with timing particular to your system when shutting down. I think it's for example not guaranteed that windows will spawn new threads when the system is shutting down. Which may be the issue. Since I cannot really replicate this bug myself, would you be up for helping me test a patched version to try and slightly defer the service shutting down some which might help with this. And also I will just add some more detailed logging to determine what actually goes wrong. If you want to help with that please paste bushnaqm@gmail (sufficiently obfuscated of course) and we can talk. Seems to be no way of sending direct messages on github unfortunately. Thanks in advance

Sure I am ready to help where I can :) , there is an alternative app like yours called colorcontrol which initiates a proper shutdown but the implementation of the app is a bit messy (no service, starts only on user login, needs a taskbar icon, messy GUI...etc). Maybe you can check how it's implemented there.

**Comment by JPersson77** [comment]
Thanks, the mentioned app runs in userland and is a bit different. I made this a service to overcome some limitations you mention but services behave a bit differently. But let me send you a message and we can try to fix :)

**Comment by JPersson77** [comment]
Thanks @mbushnaq00 for helping testing and resolve this issue. I will push a patched version which will resolve this issue for those affected.
