### ISSUE TITLE
Can You add setting that allow to choose what app listens to for not being idle and turn screenon/off ?

### ISSUE THREAD

**Issue by lukpcn** [JPersson77/LGTVCompanion#58]
On my system something is preventing the app from see that I'm idle (not using mouse or keyboard) but I have other usb game controllers attached that probably stops app from detecting idle...

Can You add a settings that will allow limiting listening to a keyboard presses only?

**Comment by JPersson77** [comment]
Hi, I will add it to the feature request list and consider it. However what you describe sounds odd. Maybe you want to try and disconnect devices until you find the culprit? Would be curious to know what controller we are talking about and if there is something to be done at the actual issue.

**Comment by dechamps** [comment]
@JPersson77 I'm not surprised. I have to keep my HOTAS (Joystick) disconnected otherwise the Windows screensaver won't kick in. I'm guessing it's a Windows limitation where Windows doesn't see the user as "idle" if there is any game controller plugged in.

**Comment by JPersson77** [comment]
HI @dechamps. Granted, I only tried with the XBOX-gamepads but they don't interfere with this functionality so it is not an universal issue. 

If you want to, try launch the user daemon with argument "-show" and it will lunch a UI where last user input is denoted. See how it behaves with the HOTAS attached/removed.

**Comment by lukpcn** [comment]
My system is a virtual pinball cabinet, I have controllers that act like mouse and have 6 axis gyroscope, windows can't enter screensaver that's why I wanted to use Your app. Limiting the check to only keystrokes would give me possibility to save my C2 a bit ;)

**Comment by lukpcn** [comment]
Here is a vid of my pinball cabinet before I put LG C2 into it: https://youtu.be/uMyyP0ypl1s

**Comment by JPersson77** [comment]
That is extremely cool!!

**Comment by JPersson77** [comment]
Hi @lukpcn so I have investigated this but come to the conclusion that I will not add an option to exclude game controllers from the user idle, unfortunately. Windows is really only exposing one api for getting the last user input and that includes mouse, keyboard and controllers with no possibility to configure. So to overcome this I started looking at the raw input model which is a lot more granular in how devices are managed. There is no problem with getting it to work in accordance with what you are requesting, but there are two severe limitations: 

- The LGTV daemeon does not receive raw input when a window with administrator rights is in the foreground
- I believe Some anti-virus software will flag the .exe as suspicious/malware when implementing the raw input model (because in essence it will look like a keylogger)

So to overcome the above two limitations I would need to run the daemon as admin and also deal with the potential risk of anti virus software flagging the software. Both of which I don't really want to do. 

On the other hand I think the driver of your controller (or the controller) is erroneously keeping windows awake so it might be worth investigating further if there are any driver updates to be found. Also you may want to check out this thread: https://github.com/JPersson77/LGTVCompanion/issues/83 

Closing the issue due to the above. If you are still totally in need of a version that will work like you mention for your pinball cabinet come to the discord channel and I can give you a version that will do it. But that version will not receive further updates since I won't keep the raw input model in the .exe for reasons stated above.

**Comment by JPersson77** [comment]
Just leaving this here as there is some progress on the issue: https://www.techradar.com/news/its-finally-game-over-for-one-of-windows-11s-oldest-and-annoying-bugs
