### ISSUE TITLE
Companion app no longer connecting?

### ISSUE THREAD

**Issue by Eden365** [JPersson77/LGTVCompanion#63]
I don't know what I have done but all of a sudden the app doesn't work for me.

https://pastebin.com/1QFYqCaU

**Comment by JPersson77** [comment]
Sorry 192.168.0.44 ....

**Comment by Eden365** [comment]
> 

This is what I have in the configure device setting of the companion app, yes?

**Comment by JPersson77** [comment]
Note to self - don't email responses as it does not work properly

It is possible the IP of your display was changed by your router. Please enter the network settings of the TV (not the app) and verify that the IP is still 192.168.0.44.

**Comment by Eden365** [comment]
> Note to self - don't email responses as it does not work properly
> 
> It is possible the IP of your display was changed by your router. Please enter the network settings of the TV (not the app) and verify that the IP is still 192.168.0.44.

all good my friend.  

Is there any programs that run on startup? I had a few in my task manager labeled "program". I turned them off and thats when the app stopped working or its because i restarted my router?

Regardless i have it working now :) thank you

**Comment by JPersson77** [comment]
There are three components, a service which should be running all the time, a UI for configuring options which you run only when you need to change the settings, and from a few versions ago also a user daemon which does a few specific things in user mode (user idle detection for example). If you disabled the LGTV daemon  you can therefore expect user idle detection to stop working (if you use it)

So, in this case it seems, from reading the log, that the service could not communicate with the TV, and I suspect it likely that your TV was assigned a new IP by your router. When you have the time maybe check that you have assigned a "static lease" in your router settings so that the TV always receives the same IP.

**Comment by JPersson77** [comment]
hi, yeah the log indicates that the display is not responding. Can you
confirm that the display is still using ip 192.168.1.44?

Kind regards Jörgen

**Comment by JPersson77** [comment]
It is possible the IP of your display was changed by your router. Please
enter the network settings of the TV (not the app) and verify that the IP
is still 192.168.9.44.

**Comment by JPersson77** [comment]
Closed due to issue resolved
