### ISSUE TITLE
LG C1 won't turn on when PC resumes from sleep

### ISSUE THREAD

**Issue by Tailslide** [JPersson77/LGTVCompanion#7]
Seems to work in other situations but not this one:

```
Mon 22:07:23 > ** System is suspending to a low power state.
Mon 22:13:47 > ** System resumed from low power state (Automatic).
Mon 22:13:47 > ** System resumed from low power state.
Mon 22:13:48 > ** System requests displays ON.
Mon 22:13:48 > Device1, spawning DisplayPowerOnThread().
Mon 22:13:48 > Device1, repeating WOL broadcast started to MAC: 24:E8:53:76:BE:C0 using network broadcast: 255.255.255.255
Mon 22:13:48 > Device1, WARNING! DisplayPowerOnThread(): connect: A socket operation was attempted to an unreachable host
Mon 22:14:15 > Device1, WARNING! DisplayPowerOnThread(): connect: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
Mon 22:14:30 > Device1, repeating WOL broadcast ended
```

**Comment by JPersson77** [comment]
Hi Tailslide,

It looks like you are sending the WOL-package to network broadcast address 255.255.255.255, i.e option 1 in the device configuration. Try changing it to option 3, i.e "broadcast address accordig to IP and subnet mask" and ensure to input the correct subnet mask. Usually the default correct subnet mask (255.255.255.0) is correct. If this does not work can you please send me the full log? Upload to pastebin or similar. Thanks!

**Comment by Tailslide** [comment]
Happened again.. this time it wasn't in sleep mode. Can't seem to find a pattern.. most of the time it works.

https://pastebin.com/Zh5S7WYk

**Comment by JPersson77** [comment]
Hi again, 

there are no obvious problems in the log. From the log I can see that resuming from low power state takes around 6 seconds ususally, which is probably indicative of the time it takes for the PC to reconnect to the LAN. Then I see in the bottom of the log two entries where the screen responded only after 20-25 seconds. Can you verify that this is because you turned the screen on manually? I will assume these are the problematic ones.

Some additional things to verify. If you are connecting via wifi check:
a) that "Quickstart+" in the TV is enabled (some users report that this is needed for the NIC of the TV to stay awake)
b) that the "HDD Eco mode" is disabled (also to avoid the NIC becoming inactive)

Also, can you check that the "power on timeout" option on the settings page is at default 40 secs. 

Some additional things to consider or try:
consider using a wired connection (at least for testing) between TV and your LAN if you aren't already. This could potentially help rule out network issues.

If the TV is performing a pixel refresh some users report that the TV won't turn on while the refresh is running. I don't have that issue myself but maybe worth be on the lookout for. You can tell if a pixel refresh is running when shutting the TV if the internal power relay does not make the characteristic clicking sound immediately after shutting off the TV. It will however click off after the pixel refresh has finished. Not likely to be your issue though I think.

**Comment by Tailslide** [comment]
Yes after 20-25 seconds I started the TV manually that was the event.

Quickstart+ is enabled
I don't see the other options you mention maybe we have different firmware? I have 3.20.80
My TV is mounted so close to the wall I'll need to pick up a right angle cable but I'll give it a shot.. I was wondering the same thing about the wifi.

Another thing I might try is starting the TV with the LG app if LGTVCompanion doesn't start it.. I'm guessing they use the same API's.  It's possible it was doing the pixel refresh not sure.

It's been working perfectly the last few days so it's a bit hard to reproduce.

**Comment by JPersson77** [comment]
Hi again, I have a CX so the firmware versions are different, but for me the setting is under settings->general->additional settings->Eco mode->HDD Eco Mode. Please keep me posted on any and all things you can do to reproduce or mitigate the issue. I suspect using a cable is most likely to fix the issue (even though it's more of a workaround of course)

**Comment by Tailslide** [comment]
After switching to wired ethernet the problem hasn't happened so must be something with how the TV handles wifi

**Comment by JPersson77** [comment]
Allright, thanks for confirming. Hope it keeps working and that using a network cable isn't too much of a nuisance

**Comment by dechamps** [comment]
Just FYI, with the C1/G1, in order for WoL to work on WiFi, you need to enable "General" > "Devices" > "External Devices" > "TV On With Mobile" > "Turn on via Wi-Fi(Networked Standby Mode)". Otherwise it won't work.

**Comment by Tailslide** [comment]
Thanks for the suggestion. Yes, I had that setting turned on.  And it worked most of the time just not 100% of the time.
