### ISSUE TITLE
chrome resizing

### ISSUE THREAD

**Issue by reaps101** [JPersson77/LGTVCompanion#71]
is there anyway to stop chrome resizing to top left corner, chrome resizes every time tv is put to sleep when companion app is set to manage tv have tried different browser firefox doesn't do it

**Comment by dechamps** [comment]
I suspect this has nothing to do with LGTVCompanion and more to do with the fact that TVs, in general, appear as disconnected when they are turned off (more specifically, they stop responding to EDID requests), which is different from how typical PC monitors behave. As a result, turning off the TV and then turning it back on is seen as Windows as a monitor disconnect and reconnect event, which can mess up window position/sizing.

I'm not sure if anything can be done to prevent this from happening. One workaround is to use a blank screensaver instead of turning off the TV. This will still prevent burn-in, but LG OLED TVs still use quite a bit of power even when displaying a black screen (~50 W, vs. ~4 W when off).

**Comment by JPersson77** [comment]
You could try turning on  "quickstart+" (CX) or "always ready" (C2) which, if I'm right, let the device keep the HDMI active and responding to EDID requests

**Comment by dechamps** [comment]
> You could try turning on "quickstart+" (CX) or "always ready" (C2) which, if I'm right, let the device keep the HDMI active and responding to EDID requests

Do you have some source on that? I just tried it on my G1 (firmware 03.33.11) and as far as I can tell it makes no difference.

**Comment by JPersson77** [comment]
Hi @dechamps no source but my own testing.  "Always ready" on C2 seem to avoid the behavior @reaps points out as the  HDMI-input remain active. I'm however interpolating that assumption that Quickstart+ does something similar for earlier models as I cannot test it myself. Unfortunately then your experince does not corroborate.

**Comment by JPersson77** [comment]
Hi again @dechamps so your comment made me think and do some additional googling. It seems "Quickstart+" and "Always ready" is NOT the same thing. They are discrete features and both exist on C2. But "always ready" is a feature which was added on 2022 models (C2, G2 etc..).

And this revelation leads me to believe there may be a in issue with the multi-monitor support in v1.8.0 for 2021 models and earlier as they (seemingly) lack the feature to keep the HDMI-input active while the display is off.

**Comment by reaps101** [comment]
hi i have a c1 and have always used Quickstart+ so can confirm that it doesn't keep the hdmi active thats why im having this problem thanks

**Comment by JPersson77** [comment]
hi @reaps101 , thanks for confirming. I suppose you could attempt fixing the issue by adding a cheap EDID emulator in the signal chain. However I tried a quick google for an HDMI2.1 compatible EDID emulator and passthrough but only came up with the $200 HDfury which is a great device but a bit overkill. Maybe your google-fu is better than mine if this is something you would be interested in.

**Comment by reaps101** [comment]
cheapest and easiest way for me to fix the problem was to just use firefox instead of chrome now when the tv turns back on firefox hasn't shrunk/resized. don't know why chrome resizes and firefox doesn't but oh well

**Comment by JPersson77** [comment]
if it works it works :)
