### ISSUE TITLE
V1.6.2 Restart problem.

### ISSUE THREAD

**Issue by KrisDee1981** [JPersson77/LGTVCompanion#84]
Everything works great on my LG42C2 but when restarting Windows TV turn off.
I have Polish Version of Windows 11 Pro, and in "Restart Words" I have put checkmarks for "restart" and "uruchom ponownie"(restart in Polish).

**Comment by JPersson77** [comment]
Hi @KrisDee1981 can you please upload your log and config.json file to pastebin and paste a lik here so I can have a look. Cheers!

**Comment by KrisDee1981** [comment]
https://pastebin.com/4A9E0rv8

https://pastebin.com/jcbDLiKd

**Comment by JPersson77** [comment]
Thank you! What immediately stands out is this from the log:

Tue 23:32:02 > WARNING! The application did not receive an Event Subscription Callback prior to system shutting down. Unable to determine if system is shutting down or restarting.

Some additional information - there is no straightforward way, known to me, for a windows service to determine if the system is restarted or shutdown. Actually this is an issue even when in user space. So the app reads a certain system event which occur when the system is shut down or rebooted. There is however the risk that this event is not always triggered in which case the state is indeterminate and the app takes the cautious approach and turn off the display. This seems to be happening all the time for you. If it is a system issue it might be hard to fix in the app, so let's start by ruling that out first.

Please open the event viewer. Create a custom view. Make it look like this:
![image](https://user-images.githubusercontent.com/77928210/204796232-24f9b630-cb2a-49c0-89d4-f2bf92c985bf.png)

and then browse through all the events (or lack thereof) to see if you have events which match your PC rebotting or shutting down. The expectation is that exactly one event occur per system power event. If you have the proper events your issue is probably a bug in the app. If you don't have the proper events it seems your windows installation does not work according to what the app is expecting and I will have to think about what can be done about that.

Thanks for helping troubleshootig!

**Comment by JPersson77** [comment]
Closing this issue due to missing user feedback and the fact that windows for unknown reasons sometimes does not write the proper events in the event log for a restart. When this happens the app will take the safe approach and shut down the display. Feel free to reopen the issue if you have gone through the suggested action above so I can try to determine if there is a bug to be resolved in how f e characters like 'ł' are treated.
