### ISSUE TITLE
Companion app not prompting pair on lgtv

### ISSUE THREAD

**Issue by Danathan-exe** [JPersson77/LGTVCompanion#85]

**Comment by Danathan-exe** [comment]
I had to reinstall windows the other day and after reinstalling the app the application no longer detected the LG display.

Heres what I have tried 

1. setting the TV to static IP instead of dhcp

2. I have reinstalled the app numerous times and have  reset both the computer and the tv.

3. I had reset the tv to defaults then re tried.

4. setting the tv to another static IP. 

5.using my network card instead of ethernet

Let me know if you guys have any solutions.

Thanks,

**Comment by Danathan-exe** [comment]
Hello, 

Update:

I installed the companion on my laptop and it immediately recognized it, going to try a fresh install of windows. 

Also, I did try to change my IP on my desktop too with no luck, along with resetting the network settings.

**Comment by Danathan-exe** [comment]
Hello,

Last and final update:

I ended up fixing the issue by reinstalling the ethernet drivers.

I hope this saves somebody else the two hours I spent on it.
 
Weird thing though it never asked to pair with the tv...

well at least it worked

Thanks,

**Comment by JPersson77** [comment]
@Zyarra and @Danathan-exe it sounds like the pairing key was invalidated (for one reason or another). To fix this you can delete the device in the configuration window and re-add it. Or you can download test version v1.8.5 from Discord https://discord.gg/7KkTPrP3fq which contais a fix for managing this situation and force re-pairing.

If you want me to have a look at why the CX's are not working start a new issue and upload the logs and we can start digging. It should work obviously.

**Comment by Danathan-exe** [comment]
__Hello @JPersson77,

I actually already fixed my problem as stated above the way I fixed it was by installing the older version of the lgtv companion and it worked. 

_Note I had to manually enter the tv info into the program anyway._

Thanks,

**Comment by JPersson77** [comment]
Hi @Danathan-exe the issue was commented on by @Zyarra so I just took the liberty of offering input. :)

Looks like there are three issues potentially in this thread.

1. automatic detection of devices on the network does not always work. _Yes this happens when windows has not yet picked it up as a digital media device. But adding manually always works._
2. manual input of MAC and IP can be made clearer. _I'm adding it to the code while typing this._
3. pairing keys might be invalidated for reasons. _Versions before v1.8.5 did not properly pick up on that but should be fixed and implemented in next public release._

**Comment by Danathan-exe** [comment]
@JPersson77 Thank you for your advice!

Thanks,
