### ISSUE TITLE
Cannot find the exe in console?

### ISSUE THREAD

**Issue by tirrorex** [JPersson77/LGTVCompanion#89]
Hello,
so i don't know if the issue is with spacing (apparently i need to put the spacing between quotes like this " \") but powershell nor the command prompt seems to be able to find the exe path.
What am i missing?
I am trying to troubleshoot why my screen wont go blank (65E8) despite beeing able to turn off with the test provided
Cheers

**Comment by JPersson77** [comment]
Hi @tirrorex 

So do I understand this correctly- if you open a command prompt at c:/program files/lgtv companion/ (or your install path) and type "LGTV Companion.exe -screenoff Device1" (don't include the double quotes and substitute 'Device'  as applicable) you get an error message that the .exe is missing? 

Another way that might help you troubleshoot why the idle function is not working is to execute "LGTVdaemon.exe -show" (again no quotes) which will show you a status window with time since last user input. From experience one of your usb devices might prevent idle and you can start unpligging devices and see in the status window which one potentially prevent idle

**Comment by JPersson77** [comment]
hi @tirrorex any feedback wrt this issue?

**Comment by JPersson77** [comment]
Closing the issue due to missing feedback on the issue. Feel free to reopen as applicable
